apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: wenderpmachado/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.ts"
            dest: .
    - image: wenderpmachado/consumers
      context: consumer
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.ts"
            dest: .
    - image: wenderpmachado/producers
      context: producer
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.ts"
            dest: .
