apiVersion: apps/v1
kind: Deployment
metadata:
  name: producers-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producers
  template:
    metadata:
      labels:
        app: producers
    spec:
      containers:
        - name: producers
          image: wenderpmachado/producers
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: producers-clusterip-srv
spec:
  selector:
    app: producers
  ports:
    - name: producers
      protocol: TCP
      port: 8001
      targetPort: 8001 # internal
