apiVersion: v1
kind: Service
metadata:
  name: producers-srv
spec:
  type: NodePort
  selector:
    app: producers
  ports:
    - name: producers
      protocol: TCP
      port: 8001
      targetPort: 8001
